title: Ben's Website
author: Benjamin Hong
description: > Made for Mr. Cohen's AP Computer Science A class.
theme: jekyll-theme-dinky

instagram_username: dun_dun_dunnnnnnn
twitter_username: aziatka8 # DO NOT include the @ character, or else the build will fail!
discord_tag: printer#3637
github_username:  bhong8989 # DO NOT include the @ character, or else the build will fail!
